In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('/Users/vidhi/college baby/sem 6/Topics in EconRes/FinalPaperMaterial/Data/Mittal et al data/panchayat_ID_MIS_index_mapping.csv', usecols=range(9))
df.head()

,Panchayat_ID,Gram_panchayat_name,Subdistrict census code,Subdistrict name,District census code,District name,State census code,State name,mis_index
0,221810,pitchikalapadu,4730,Yetapaka,541,visakhapatnam,28,andhra pradesh,NaN
1,221811,kannaigudem,4730,Yetapaka,541,visakhapatnam,28,andhra pradesh,NaN
2,221812,laxmipuram,4730,Yetapaka,541,visakhapatnam,28,andhra pradesh,NaN
3,221813,ramagopalapuram,4730,Yetapaka,541,visakhapatnam,28,andhra pradesh,NaN
4,221814,nallakunta,4730,Yetapaka,541,visakhapatnam,28,andhra pradesh,NaN

In [4]:
df.describe()

,Panchayat_ID,Gram_panchayat_name,Subdistrict census code,Subdistrict name,District census code,District name,State census code,State name,mis_index
count,217930,217458,217930,217930,217930,217619,217930,217930,115223
unique,209749,153584,4816,5161,860,853,432,432,109732
top,106350,kochas,202,Lalganj,191,azamgarh,9,uttar pradesh,451.0
freq,2,1053,535,823,1855,1855,57611,57611,3

In [9]:
df.to_csv('/Users/vidhi/college baby/sem 6/Topics in EconRes/FinalPaperMaterial/Data/Mittal et al data/panchayat_ID_MIS_index_mapping.csv', index=False)